config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
  resources :items do
    member do
      patch :complete
    end
  end

  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  # These are methods for Item we can use in the console:
  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # Run find_item method before show, edit and update
  before_action :find_item, only: [:show, :edit, :update, :destroy, :complete]

  def index
    # Store all items in an array and order by date descending
    @items = Item.all.order("created_at DESC")
  end

  def new
    # Create variable with model
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      # If an items is added, go to homepage
      redirect_to root_path
    else
      # Otherwise, stay in the "new" page
      render 'new'
    end
  end

  def show
    # before_action will run
  end

  def edit
    # before_action will run
  end

  def update
    # before_action will run

    if @item.update(item_params)
      # If item is updated, go to "show" page
      redirect_to item_path(@item)
    else
      # Otherwise, stay in the "edit" page
      render 'edit'
    end
  end

  def destroy
    # before_action will run

    @item.destroy
    redirect_to root_path
  end

  def complete
    # before_action will run

    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%# Form for @item variable from items_controller %>
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Title" %>
  <%= f.input :description, label: "Description" %>
  <%= f.button :submit, "Save" %>
<% end %>

app/views/items/index.html.erb
<h1>My Tasks</h1>

<button type="button"><%= link_to 'New Task', new_item_path %></button>

<% @items.each do |item| %>
  <% if item.completed? %>
    <h2><s><%= link_to item.title, item %></s></h2>
    <p><%= time_ago_in_words(item.completed_at) %> ago.</p>
    <%= link_to complete_item_path(item), method: :patch do %>
      <input type="checkbox" checked />
    <% end %>

  <% else %>
    <h2><%= link_to item.title, item %></h2>
    <p><%= item.description %></p>
    <%= link_to complete_item_path(item), method: :patch do %>
      <input type="checkbox" />
    <% end %>
  <% end %>

<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%# Form for @item variable from items_controller %>
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Title" %>
  <%= f.input :description, label: "Description" %>
  <%= f.button :submit, "Create Item" %>
<% end %>

app/views/items/show.html.erb
<h2><%= @item.title %> </h2>
<p><%= @item.description %> </p>

<%= link_to 'Go Back', root_path %>
<%= link_to 'Edit', edit_item_path %>
<%= link_to 'Delete', item_path(@item), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>